//GENERAL ERRORS
export const INTERNET_ISSUE = 'INTERNET_ISSUE';

//FORM ACTIONS
export const EMAIL_CHANGE = 'EMAIL_CHANGE';
export const PASSWORD_CHANGE = 'PASSWORD_CHANGE';
export const PASSWORD_CONFIRM_CHANGE = 'PASSWORD_CONFIRM_CHANGE';
export const FORM_SUBMIT = 'FORM_SUBMIT';
export const FORM_SUBMIT_FINISH = 'FORM_SUBMIT_FINISH';
export const FORM_ERROR = 'FORM_ERROR';
export const CLEAR_ERROR_ON_TYPE = 'CLEAR_ERROR_ON_TYPE';


//Login WIth Email
export const LOGIN_USER_TO_FORGOT_PASSWORD = 'LOGIN_USER_TO_FORGOT_PASSWORD';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_EMAIL_INVALID = 'LOGIN_USER_EMAIL_INVALID';
export const LOGIN_USER_INVALID_CREDENTIALS = 'LOGIN_USER_INVALID_CREDENTIALS';
export const LOGIN_INPUTS = 'LOGIN_INPUTS';
export const RESET_EMAIL_SUCCESS = 'RESET_EMAIL_SUCCESS'; 

// Forgot Password
export const RESET_PASSWORD_MODIFY_EMAIL = 'RESET_PASSWORD_MODIFY_EMAIL';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_EMAIL_SENT = 'RESET_PASSWORD_EMAIL_SENT';
export const RESET_PASSWORD_USER_NOT_FOUND = 'RESET_PASSWORD_USER_NOT_FOUND';
export const RESET_PASSWORD_INVALID_EMAIL = 'RESET_PASSWORD_INVALID_EMAIL';
export const RESET_PASSWORD_OTHER_ERROR = 'RESET_PASSWORD_OTHER_ERROR';
export const NAVIGATION_BACK = 'Navigation/BACK';

// REGISTER USER
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';
export const REGISTER_USER_PASSWORD_DONT_MATCH = 'REGISTER_USER_PASSWORD_DONT_MATCH';
export const REGISTER_PASSWORD_WEAK = 'REGISTER_PASSWORD_WEAK';
export const REGISTER_USER_EMPTY_PASSWORD = 'REGISTER_USER_EMPTY_PASSWORD';

// books
export const SEND_BOOKS = 'SEND_BOOKS';
